### ISSUE TITLE
Version 1.11.2-1.0.0 Published on Curse does not contain any recipes.

### ISSUE THREAD

**Issue by zwof03** [GodsVictory/MobRecipes#2]
Installed the mod, noticed that none of the recipes were showing up so i checked if the mod file was in the mods folder etc etc and noticed that the file was very small. So i compared the size with the previous 1.10.2 version, which was larger.
Opened the jar and sure enough the "com" folder is missing.

**Comment by GodsVictory** [comment]
new version has been uploaded
